language: python

python:
  - '3.8'

before_script:
  - pip install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip
  - unzip chromedriver_win32.zip -d /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/selenium/webdriver/chrome/
  - rm chromedriver_win32.zip
  - export CHROME_BIN=chromium-browser

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver
  - python manage.py test
