language: python

python:
  - '3.8'

addons:
  chrome: stable

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver.exe
  - python manage.py test functional_tests
