language: python

python:
  - '3.8'

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver
  - python manage.py test functional_tests
