language: python

python:
  - '3.8'

addons:
  chrome: stable

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver
  - python manage.py test functional_tests
