language: python

python:
  - '3.8'

sudo: required

addons:
  chrome: stable

before_script:
  - wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
options = webdriver.ChromeOptions()
options.binary_location = '/usr/bin/chromium-browser'
options.add_argument("--no-sandbox")
options.add_argument("--no-default-browser-check")
options.add_argument("--no-first-run")
options.add_argument("--disable-default-apps")
driver = webdriver.Chrome('/home/travis/virtualenv/python3.8   /chromedriver',chrome_options=options)

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver
  - python manage.py test functional_tests
