language: python

python:
  - '3.8'

addons:
  chrome: stable

before_script:
  - pip install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip
  - mkdir /home/travis/Webdriver/bin/
  - sudo unzip chromedriver_win32.zip -d /home/travis/Webdriver/bin/

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver
  - python manage.py test functional_tests
