language: python

python:
  - '3.8'

before_script:
  - pip install -r requirements.txt
  - https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip
  - wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_win32.zip

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script: python manage.py test
