language: python

python:
  - '3.8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script:
  - whereis chromedriver
  - python manage.py test
